spring:
  application:
    name: grupo-2

  datasource:
    url: jdbc:mysql://localhost:3306/3
    username: root
    password: AngelBeats2018
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    cache: false

