spring:
  application:
    name: grupo-2
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  datasource:
    url: jdbc:mysql://localhost/3
    username: root
    password: AngelBeats2018
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    cache: false

server:
  error:
    path: /error
    whitelabel:
      enabled: false

